### ISSUE TITLE
Resolving issues with Red Hat Insights Advisor lab - console.redhat.com tab not showing

### ISSUE THREAD

**Issue by craig-br** [rhel-labs/instruqt#142]
**Resolving issues with Red Hat Insights Advisor lab**
- First challenge. The `RHEL Web Console` tab not working. Screenshot attached.
![Screenshot 2023-01-04 at 12 34 18](https://user-images.githubusercontent.com/42829306/210556690-5fb3d923-32b2-4a06-99e9-a92cb6a4e70c.png)

**Comment by myee111** [comment]
Which browser are you using @craig-br ?

**Comment by myee111** [comment]
@craig-br as well, is this `insights-workshop`?

**Comment by craig-br** [comment]
@myee111 I believe it is `insights-workshop`. https://lab.redhat.com/tracks/insights-workshop
 
- Chrome Version 108.0.5359.124 (Official Build) (arm64) on Mac
- Firefox 108.0 (64-bit) on Fedora 37

I think it's because it's running in an iframe. We had this issue with other Instruqt labs and web consoles. Browser debugger output:

```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sentry.io/api/1218778/envelope/?sentry_key=95926e24757b46c7bab55f8f49f72857&sentry_version=7&sentry_client=sentry.javascript.react%2F7.28.1. (Reason: CORS request did not succeed). Status code: (null).```

**Comment by smcbrien** [comment]
I've verified the problem.  However, the lab does not require Web Console.  We'll either update the lab to open Web Console in a separate browser tab (which is the method that works on the other labs that utilize Web Console) or we'll remove the tab from the environment thereby 'fixing the glitch'.
