### ISSUE TITLE
idm-workshop-1 - Typos/Grammar

### ISSUE THREAD

**Issue by charles-shaw** [rhel-labs/instruqt#156]
Feed is related to idm-workshop-1

- IdM leverages sssd within these distributions -->  IdM leverages **System Security Services Daemon (SSSD)** within these distributions 
- Identity Management is fully supported for servers and clients at no additional cost, as **it is included within** your Red Hat Enterprise Linux subscription
- Labsetup.sh - There is no output, could an output print the 'Static hostname' from 'hostnamectl'? Which would then be aligned w/ instructions of pinging the hostname
- 'Enrolling Systems' - In this section, you will install the IdM client on a Red Hat Enterprise **Linxu** 
- Install packages on system - Small and likely irrelevant detail, YUM is used over DNF
-  'Sudo Rule Management' - When changes are required they happen near **instantaniously** throughout the environment - adding access or revoking access is immediate.

**Comment by parmstro** [comment]
The above, plus some other typos and issues have been resolved with the latest push. Will update this repo once other changes are complete.
