### ISSUE TITLE
HMS Lab fixes needed

### ISSUE THREAD

**Issue by tichomir** [rhel-labs/instruqt#165]
Couple of findings during the LAB execution
* Screenshot will have to be updated in certain places 

Page 1 - where the login screen is, the top bar of console.dot has changed and the favorites is not there anymore
Page 1 - Beta is not beta anymore, it says Preview
Page 2 - With the expected update in couple of days from now, the Repositories configuration is going to be moved out from the settings menu. It should be found in the left hand side bar. 
Page 2 - we need to advise participants to think of a random repository, or if they decide to just use what is available. the reason being the validation is based on repository URL, so even if they put the different names they might still get an error that the repo sexists
Page 3 - for some reason, today, if you type Image in the search bar, it will show you something else, you need to type in Builder
Page 3 - I will try to change the screenshot where we see names of customers such as ASML and REWE 
Page 3 - The source is labeled RHTE1
Page 3 - The IB Wizard has changed, so update of the screenshot is needed
Page 3 - We shall advise participants to use for example their names, or pet names, or whatsoever to avoid duplication of names. IB does not do such validation, thus they might lose their own image!
Page 4 - The Launch wizard changed too, now it supports AWS Launch templates
Page 5 - You don't need to run the rhc connect anymore. It is enabled by default. 
Page 6 - The Pre Upgrade check analysis is executable only in case you install OS from a RHEL 8 Images. So I guess it would be good to suggest to work with RHEL 8 Images rather than RHEL 9.

**Comment by mshriver** [comment]
Beta/Preview screenshots have been updated and reflect the updated toolbar with Preview on (not including favorites).

**Comment by mshriver** [comment]
I have not observed application/service search not working with `Image`. There are different search bars to use, one in the services menu, separate from the top bar search.

**Comment by RCMariko** [comment]
> I have not observed application/service search not working with `Image`. There are different search bars to use, one in the services menu, separate from the top bar search.

page 3 - once I click on "Services" I needed to click n "View all services" to get to the search bar that I believe should be used.

**Comment by rverdile** [comment]
Seeing an additional issue in the "Launch an Image" activity. Might be related to that ubi-init PR. 

[These commands](https://github.com/mshriver/instruqt/blob/f44ac75cc998f34157caa008f68f736913c0700d/satellite-online/04-launch-instance/assignment.md?plain=1#L103-L121) are not showing the same results for me. I guess because the ubi-init package is not installed?

**Comment by ehelms** [comment]
The track (https://github.com/rhel-labs/instruqt/blob/satellite-basics-updates/satellite-online/track.yml) (and folder naming scheme) needs to be changed away from satellite-online / Satellite Online to updated branding.

**Comment by myee111** [comment]
> The track (https://github.com/rhel-labs/instruqt/blob/satellite-basics-updates/satellite-online/track.yml) (and folder naming scheme) needs to be changed away from satellite-online / Satellite Online to updated branding.

fixed

**Comment by myee111** [comment]
fixed
