### ISSUE TITLE
rhel-services workshop fixes

### ISSUE THREAD

**Issue by RCMariko** [rhel-labs/instruqt#182]
Page 4 - menu screenshot of left-hand navigation looks very differeent & doesn't show "Image Builder" (I'm logged in as the test user)
    I found it by searching for Image Builder again.
    Left hand menu shows "Inventory-->Images"

Page 6 - Don't see the RHBA-2023:2620

**Comment by myee111** [comment]
Both problems fixed. Thanks @RCMariko
