### ISSUE TITLE
tlog lab, sssd fails after enabling session logging

### ISSUE THREAD

**Issue by nlager** [rhel-labs/instruqt#458]
An issue has been reported, that after the step in the tlog lab, where you enable session recording via the web console, sssd fails to start, and session logging is not enabled.

**Comment by nlager** [comment]
I ran through the lab, and found that at step 4, when tlog is enabled, the sssd service then starts to fail with the error:

```
Jan 18 20:57:12 rhel sssd_be[4102]: Starting up
Jan 18 20:57:12 rhel sssd[4094]: Exiting the SSSD. Could not restart critical service [nssfiles].
Jan 18 20:57:12 rhel systemd[1]: sssd.service: Main process exited, code=exited, status=1/FAILURE
```

I dug into nssfile's log file and found:

```
   *  (2024-01-18 20:57:12): [be[nssfiles]] [dp_module_open_lib] (0x0010): Unable to load module [proxy] with path [/usr/lib64/sssd/libsss_proxy.so]: /usr/lib64/sssd/libsss_proxy.so: cannot open shared object file: No such file or directory
```

I installed the package sssd-proxy which provides the above missing library, and now sssd starts properly, and session logging works. 

this feels like a package dependency bug to me.

**Comment by nlager** [comment]
I have added a work-around to this lab, installing sssd-proxy in the setup script.

**Comment by smcbrien** [comment]
I'm going to close this issue as the updated pre-provision script resolves it.
