### ISSUE TITLE
session recording lab playback seems broken in cockpit

### ISSUE THREAD

**Issue by parmstro** [rhel-labs/instruqt#465]
Session Recording playback seems to be broken in the cockpit UI. The terminal window display in the playback window stays blank and the text below does not scroll or and displays unprintable characters. 

Chrome browser on RHEL9

Terminal playback is unaffected. 

I will attempt on firefox as well and post results.

**Comment by myee111** [comment]
Hey Nate, Eric,
Could one of you take this on please? I'm busy with the satellite summit
lab.

**Comment by parmstro** [comment]
Can't even log in to the web console using Firefox. Just keeps going back to the login window for the console.

**Comment by benblasco** [comment]
@parmstro I had the same issue, but it works in a private browsing window under firefox for me.

**Comment by smcbrien** [comment]
This is fixed now.

**Comment by parmstro** [comment]
Yes! Thank you!

Firefox seems broken tho. Everyone in my session had issues with firefox
today.
Also, SQLServer session recording is broken, seems like an OS image update
thing. mssqlserver does not deploy ...

I can look into it next week, but if someone else has cycles please.

Cheers,

PA


Paul Armstrong
Principal Technical Specialist
Red Hat Technical Sales Organization
647-285-0044
