### ISSUE TITLE
Crypto Policies Lab 1 use tmux - causes paste issues

### ISSUE THREAD

**Issue by parmstro** [rhel-labs/instruqt#466]
Running the crypto policies lab for a workshop tomorrow. The default terminal appears to be running tmux. When trying to paste into the window on RHEL9 chrome, the terminal shows the underlying tmux context menu and it intercepts the paste causing unpredicable behaviour like creating a new tmux window...

Can't paste any of the lab commands into the terminial window, requiring all users to type.

Again, will try this with firefox and post results to this issue.

**Comment by parmstro** [comment]
![image](https://github.com/rhel-labs/instruqt/assets/5768297/9adc2163-d76e-45c6-96cc-0ceb5294f49b)

**Comment by parmstro** [comment]
In firefox, the same thing occurs, however, if I move the mouse cursor off the browser context menu, the underlying tmux context menu disappears and the browser context menu remains. Clicking on paste in the floating browser context menu pastes the copied content normally into the window.

Works, but still not intended behaviour. 

I would recommend disabling tmux in this lab until we can sort it out.

**Comment by parmstro** [comment]
P.S. Copy and Paste work normally in both Chrome and Firefox for the session-recording lab running on RHEL9 laptop.

**Comment by smcbrien** [comment]
How are you pasting?  using the right-click menu-paste?  Keyboard shortcut?
(I think this is generally not working).

-STM

**Comment by parmstro** [comment]
Your latest update fixed it Scott
Thanks!
