### ISSUE TITLE
Images missing from tlog lab

### ISSUE THREAD

**Issue by benblasco** [rhel-labs/instruqt#472]
The images are missing from sections 3, 6, 7 in the tlog lab at https://red.ht/tlog-lab

Below is a screenshot captured from screen 3 showing links to "an example image" rather than the actual required screen shot.

![f42ffe996bc523f188237b8131c29fda](https://github.com/rhel-labs/instruqt/assets/42140583/fc7ae099-7f95-4a8e-8cc0-32b4e64b5f9d)

Please let me know if you need any more info to help diagnose/troubleshoot the issue.

**Comment by smcbrien** [comment]
Images rendered in my latest provision of the lab.  I think this is working properly.
