### ISSUE TITLE
Performance observability lab refers to yum instead of DNF

### ISSUE THREAD

**Issue by benblasco** [rhel-labs/instruqt#475]
The description of the lab refers to observing the behaviour of the `yum` command. We should be referring to `dnf` as yum is either deprecated or aliased in RHEL 8 and 9.

![image](https://github.com/rhel-labs/instruqt/assets/42140583/485fc97e-f3dd-44e6-a981-a39360208b8b)

Through the lab it also uses `yum` commands to install packages, e.g.
`yum install -y kernel-devel-$(uname -r) bcc-tools`

I appreciate that converting to `dnf` _may_ take a little more than just `s/yum/dnf/g` but think it's of value for us to demonstrate our most recent tooling.

Lab can be found at https://red.ht/bcc

**Comment by smcbrien** [comment]
Updates have been applied, the lab now uses dnf for all package mangement.
