### ISSUE TITLE
firewall-system-role lab: Rename hosts from rhel/rhelvm for clarity

### ISSUE THREAD

**Issue by benblasco** [rhel-labs/instruqt#486]
Feedback from the RHEL 9 virtual workshop run in Australia today.

The attendee said that the naming of the two VMs in the lab was confusing:
- rhel = control node running ansible playbook
- rhelvm = host being configured by the ansible playbook

I am inclined to agree with this feedback and suggest that we could rename the hosts as follows:
- rhel -> controlvm
- rhelvm -> rhelvm (same)
or something similar.

Happy to do this myself if somebody provides feedback agreeing with this in principle.  I realise that the update has to cover the host names, the docs, and the headings for each tab.

**Comment by myee111** [comment]
fixed
