### ISSUE TITLE
Edge-Management-Lab: Lab system in GCP not enabled for virtualization; VM launch/boot fails

### ISSUE THREAD

**Issue by pscojr** [rhel-labs/instruqt#526]
During "Install image on your edge device" section, we are to create a VM on the lab RHEL system.  This VM does not boot successfully and it appears the the lab VM is being build in Google without Virtualization capabilities enabled.  This was working a few days ago.

See attached images.
![Screenshot from 2024-07-30 10-54-46](https://github.com/user-attachments/assets/f9e83d1d-39ce-4bee-bb3a-ccfb9c8d6f75)
![Screenshot from 2024-07-30 10-56-55](https://github.com/user-attachments/assets/0cc16181-9876-4152-b137-c28e20d3d392)

**Comment by myee111** [comment]
Sorry, we've discontinued this particular lab.
