### ISSUE TITLE
image-mode-basics: VM login shell is not appearing

### ISSUE THREAD

**Issue by adahia** [rhel-labs/instruqt#529]
after the VM has been started using the "virsh start bootc" command, the log in shell is not appearing, looks like the start is stuck:

Connected to domain 'bootc'
Escape character is ^] (Ctrl + ])

I refreshed the console and started the lab twice with the same results

**Comment by nzwulfin** [comment]
Thanks for the report.

It looks like this was due to nested virtualization being disabled in the lab. This should be working now.

**Comment by nzwulfin** [comment]
Fixes added in #530
