### ISSUE TITLE
convert2rhel lab: Conversion does not work since retirement of CentOS repositories

### ISSUE THREAD

**Issue by benblasco** [rhel-labs/instruqt#538]
The lab does not work as the host still points to mirror.centos.org.  We must update the instructions to add the steps to point the host to vault.centos.org:

https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html-single/converting_from_a_linux_distribution_to_rhel_using_the_convert2rhel_utility/index#proc_preparing-for-a-rhel-conversion_converting-using-the-command-line

**Comment by adahia** [comment]
I hope this is the same issue I faced, and the reason is that the link to the GPG no longer works.

use the new one: 
curl -o /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release https://access.redhat.com/security/data/fd431d51.txt 

Tested and Worked :D

**Comment by myee111** [comment]
ack. I'll take a look at this today. I thought this was fixed several months ago.
