### ISSUE TITLE
Satellite Basics failing to provision

### ISSUE THREAD

**Issue by kush-gupt** [rhel-labs/instruqt#582]
Hello, the Satellite Basics lab I accessed from https://www.redhat.com/en/satellite-basics-lab is constantly giving me this error:

`Failed to start track
Unable to start track, please try again`

I want to leave more logs but that's all I get from Instruqt :(

**Comment by myee111** [comment]
I've deprecated this lab. It appears the lab.redhat.com link hasn't been updated. Here's the updated link. Thank you for letting me know! https://red.ht/satellite-basics-workshop
