### ISSUE TITLE
insights-vulnerability lab seems broken since subscription manager changes.

### ISSUE THREAD

**Issue by nlager** [rhel-labs/instruqt#98]
Seems that the insights-vulnerability lab is now no longer registering to insights at start-up.  I suspect the changes to the registration process broke it?  I will investigate

**Comment by myee111** [comment]
I was just about to update this lab. I'll take a look at this problem. Thanks for flagging this up.

**Comment by nlager** [comment]
i just started poking at it, since I needed to do some work on it anyway.  It seems that you did not break it, but something is still going on.  

The sub-manager commands that register the host, and then the rhc command to connect it are all still present, all still ran without error, but the host doesn't appear to be registered to insights when its done. 

Even manually running insights-client --register doesn't appear to fix the problem. 

```
root@rhel-8332e:~# rhc status
Connection status for rhel-8332e:

● Connected to Red Hat Subscription Management
● Not connected to Red Hat Insights
● The Red Hat connector daemon is active

Manage your Red Hat connector systems: https://red.ht/connector
root@rhel-8332e:~# 
```

**Comment by myee111** [comment]
this went away when we changed the image to 9.1
